### ISSUE TITLE
Decouple and overhaul snapshot APIs

### ISSUE THREAD

**Issue by damianh** [NEventStore/NEventStore#336]
My thoughts on this:
- In many ways, snapshots can be projected to, and read from the read store. 
- Snapshots should be discardable and rebuildable. They may not be needed to be stored along side the main event store at all and can be put into something that is not treated with the same degree of concern wrt to loss / failure.
- Many people don't bother with snapshots at all. Uses of some of the higher performing stores (GetEventStore / Mongo) may not even need snapshots.
- Having a separate API will allow users to mix and match storage event store and snapshot store, i.e. Sql for events, RavenDB for snapshots.
- Reducing the API surface for the event storage will hopefully open it up to other storage  engines that would have difficulty supporting snapshot storage due to the querying requiments (i.e. GetEventStore, Azure Blob, S3 etc)

**Comment by andreabalducci** [comment]
on mongo we implemented automatic snapshots, it's useful even with mongo.
I've to check if we can add in the snapshots the commit ids to enable idempotency on the aggregate level without loading all the commits.

**Comment by warappa** [comment]
@damianh
For your consideration:
I think in the current implementation there's support for only 1 *type* of snapshot (aka. memento) per stream.

If you have ***multiple* aggretates** using the ***same* stream** (think: different view-points of the same thing like `Resource` - `OrderableResource` - `StoreableResource`), each aggregate-type should have its own snapshots and memento-types (ie. `ResourceMemento` - `OrderableResourceMemento` - `StoreableResourceMemento`)
So if the API would allow to also filter by the memento-type used in the respective snapshots this use-case would be supported.

Maybe something like `IPersistStreams.GetSnapshot(string bucketId, string streamId, int maxRevision, Type mementoType = null)` .
It could check the value of a to-be-added `MementoType` column in the snapshots-table and ignore it, if `mementoType == null`

In `GetById` the repository could pass the memento-type to `GetSnapshot` in https://github.com/NEventStore/NEventStore/blob/master/src/NEventStore/CommonDomain/Persistence/EventStore/EventStoreRepository.cs#L54 - but then the **concrete memento-type would have to be somehow extracted from the concreate aggregate-type**.

 - Maybe if `IAggregate` had a member like `Type GetMementoType()`, the memento-type could be extracted. But then an empty aggregate-instance would be necessary the receive it...
 - Maybe `IMemento` could be refactored to `IMemento<TForAggregate>` and be resolved by scanning the assembly...
 - Or: call the check-column `ForAggregateType` instead of `MementoType` and use the concrete aggregate-type. No further changes to the API other than ' IPersistStreams.GetSnapshot(...)` would be necessary.

What do you think?
