### ISSUE TITLE
Allow extending JsonSerializer with custom JsonConverter's

### ISSUE THREAD

**Issue by mikhailshilkov** [NEventStore/NEventStore#419]
I need to be able to customize the serialization of some classes that I send to the event store. I created a custom `JsonConverter` but there's no way to make `NEventStore.Serialization.JsonSerializer` use it.
It would be nice to have an optional constructor which would accept a list of converters.

**Comment by fschmied** [comment]
The problem is that NEventStore internalizes all the Json.NET types, including `JsonConverter`. So it's not just a matter of adding an optional constructor, it's also a design decision of how to expose those `Newtonsoft.Json` types.

Options, AFAICS:

1. No longer internalize Json.NET, instead just reference it via NuGet.
  - Pro: NEventStore can then expose the actual `JsonSerializer`, `JsonConverter`, etc. types to the user.
  - Con: NEventStore ties its users to a specific (range of) versions of Json.NET. Incompatibilities can arise.
1. Keep internalizing Json.NET and have NEventStore users implement their own NEventStore serializers if they need to configure Json.NET. (This is how it is now.)
  - Pro: NEventStore supports Json out of the box without tying its user to a specific (range of) Json.NET versions.
  - Con: Repetitive work needs to be performed by users as soon as they need to customize serialization.
1. Keep internalizing Json.NET in the main NEventStore NuGet package, but add another `NEventStore.Serialization.Json` package that contains an additional JSON serializer, implemented via a public NuGet reference to Json.NET.
  - Pro: Combines positive effects of options 1 and 2.
  - Con: There needs to be a version of the package for every maintained NEventStore version and every supported (range of) Json.NET version. This can quickly turn into an unmaintained mess, especially now that NEventStore doesn't really have an owner any more.
1. Keep internalizing Json.NET in the main NEventStore NuGet package, but add an abstraction for common configuration options, such as `JsonConverter`, `TypeNameHandling`, etc.
  - Pro: NEventStore supports Json out of the box without tying its user to a specific (range of) Json.NET versions.
  - Pro: NEventStore users can adjust the most important Json.NET configuration options without any hurdles.
  - Con: Still needs one of the other options as soon as more complex configuration is required.
  - Con: Might end up duplicating much of the public API of Json.NET in NEventStore, which isn't exactly maintenance-friendly either.

**Comment by gregoryyoung** [comment]
5) keep internalizing and provide a copy/paste sample

On Sat, Jan 2, 2016 at 5:08 PM, Fabian Schmied <notifications@github.com>
wrote:

> The problem is that NEventStore internalizes all the Json.NET types,
> including JsonConverter. So it's not just a matter of adding an optional
> constructor, it's also a design decision of how to expose those
> Newtonsoft.Json types.
>
> Options, AFAICS:
>
>    1. No longer internalize Json.NET, instead just reference it via
>    NuGet.
>       - Pro: NEventStore can then expose the actual JsonSerializer,
>       JsonConverter, etc. types to the user.
>       - Con: NEventStore ties its users to a specific (range of) versions
>       of Json.NET. Incompatibilities can arise.
>    2. Keep internalizing Json.NET and have NEventStore users implement
>    their own NEventStore serializers if they need to configure Json.NET. (This
>    is how it is now.)
>       - Pro: NEventStore supports Json out of the box without tying its
>       user to a specific (range of) Json.NET versions.
>       - Con: Repetitive work needs to be performed by users as soon as
>       they need to customize serialization.
>    3. Keep internalizing Json.NET in the main NEventStore NuGet package,
>    but add another NEventStore.Serialization.Json package that contains
>    an additional JSON serializer, implemented via a public NuGet reference to
>    Json.NET.
>       - Pro: Combines positive effects of options 1 and 2.
>       - Con: There needs to be a version of the package for every
>       maintained NEventStore version and every supported (range of) Json.NET
>       version. This can quickly turn into an unmaintained mess, especially now
>       that NEventStore doesn't really have an owner any more.
>    4. Keep internalizing Json.NET in the main NEventStore NuGet package,
>    but add an abstraction for common configuration options, such as
>    JsonConverter, TypeNameHandling, etc.
>       - Pro: NEventStore supports Json out of the box without tying its
>       user to a specific (range of) Json.NET versions.
>       - Pro: NEventStore users can adjust the most important Json.NET
>       configuration options without any hurdles.
>       - Con: Still needs one of the other options as soon as more complex
>       configuration is required.
>       - Con: Might end up duplicating much of the public API of Json.NET
>       in NEventStore, which isn't exactly maintenance-friendly either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/419#issuecomment-168407421>
> .
>



-- 
Studying for the Turing test

**Comment by mikhailshilkov** [comment]
What's the added benefit of this internalization? As of today, people can still use Newtonsoft attributes to control serialization. If NEventStore decides to switch to another JSON serializer, it's going to be a breaking change for many clients, so I'd rather make it an explicit change.

**Comment by gregoryyoung** [comment]
Try using your own version of newtonsoft in say your restful service ...

On Sat, Jan 2, 2016 at 5:26 PM, Mikhail Shilkov <notifications@github.com>
wrote:

> What's the added benefit of this internalization? As of today, people can
> still use Newtonsoft attributes to control serialization. If NEventStore
> decides to switch to another JSON serializer, it's going to be a breaking
> change for many clients, so I'd rather make it an explicit change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NEventStore/NEventStore/issues/419#issuecomment-168409436>
> .
>



-- 
Studying for the Turing test

**Comment by fschmied** [comment]
@mikhailshilkov NEventStore doesn't internalize in order to to hide the fact it uses Json.NET, but to allow people to use a different version of Json.NET alongside NEventStore.

**Comment by jjrdk** [comment]
If you wanted to go with option 3, then you could add it to the [NEventStore.Contrib](https://github.com/jjrdk/NEventStore.Contrib) project.

However I'd recommend creating your own ISerializer implementation and adding the necessary converters there, since the converters will be specific for you. Implementing the ISerializer interface is only really boilerplate code, so does not add any complexity to your project.

**Comment by mikhailshilkov** [comment]
Yes, that's what I did - I created my own serializer based on existing serializer code + extra constructor parameters.

**Comment by AGiorgetti** [comment]
That was the same solution I adopted in the past, I've created a reference project to use as a starting point to create your very own version of the serializer. Basically it's a copy/paste from the code you have inside the main NEventStore repository:

https://github.com/AGiorgetti/NEventStore.Serialization.Json

I'm talking with the guys of the team to see if we can move this to the official NEventStore repositories

**Comment by andreabalducci** [comment]
moved @AGiorgetti sample repo to https://github.com/NEventStore/NEventStore.CustomJsonSerializerSample
Wiki & docs needs to be updated.

**Comment by alkampfergit** [comment]
closed because of inactivity and because @AGiorgetti created a reference implementation to solve the issue.
