### ISSUE TITLE
IObserveCommits Start should accept cancellationtoken

### ISSUE THREAD

**Issue by btrepp** [NEventStore/NEventStore#440]
I'm not 100% around the implementation and where it is used, but shouldn't IObserveCommits accept a cancellationtoken?.

In [IObserveCommits.cs](https://github.com/NEventStore/NEventStore/blob/f88da183a612f70be5419e94692e1191675819dd/src/NEventStore/Client/IObserveCommits.cs)

Should be
```
public interface IObserveCommits : IObservable<ICommit>, IDisposable
    {
        Task Start(CancellationToken cancel);

        void PollNow();
    }
```

This way anything starting the observer in an async method can cancel the observer gracefully/passthrough higher level cancellation tokens.

**Comment by AGiorgetti** [comment]
I'm closing this issue because we have changed the PollingClient design quite a bit and that interface is gone.

What you can find in the core is now a very basic implementation (look at the PollingClient2 class) that, while it can be used, it is considered a starting point from which build your own PollingClient implementation.

We can come up with something to gather up the different proposals of PollingClients implementations made by the community, maybe in the wiki or in a separate dedicated repository, or why not in the core itself if people submitt those as pull requests.
