### ISSUE TITLE
Stream cannot add events out of order

### ISSUE THREAD

**Issue by DR9885** [NEventStore/NEventStore#452]
I have a job-service that spawns multiple events. And if one event fails to send, it still processes the rest. It will then store that event failure for replay. However, because of this, I may receive events out of order. however these events have time-stamps that allow me to figure out the correct order of the events... In the current Implementation of NEventStore, I can only append events to the end... It would be nice if I could append events somewhere in the middle if needed.

**Comment by maxcherednik** [comment]
I think that the ordering should be done on the read side.

**Comment by gregoryyoung** [comment]
I think the last sentence says it all " I can only append events to the end... It would be nice if I could append events somewhere in the middle if needed." except it wouldn't be an append at that point. Why not put your date in metadata and reorder how you see fit?

**Comment by fschmied** [comment]
"... except it wouldn't be an append at that point"

And, IMO a very important consequence, inserting rather than appending would remove the queuing/catchup guarantees the event store can make. Currently, readers can always catch up from the last "position" they've read - with inserting, this would no longer work.

Regards,
Fabian

----- Ursprüngliche Nachricht -----
Von: "Greg Young" <notifications@github.com>
Gesendet: ‎13.‎01.‎2017 09:36
An: "NEventStore/NEventStore" <NEventStore@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: Re: [NEventStore/NEventStore] Stream cannot add events out of order(#452)

I think the last sentence says it all " I can only append events to the end... It would be nice if I could append events somewhere in the middle if needed." except it wouldn't be an append at that point. Why not put your date in metadata and reorder how you see fit?

**Comment by DR9885** [comment]
Metadata sounds like a great idea, that works for me, thanks!

**Comment by adebisi-fa** [comment]
Any idea when this issue will be closed, as it appears it has been resolved?
