### ISSUE TITLE
.NET Core migration: replace the custom logger wrappers with the new Microsoft.Extensions.Logging classes

### ISSUE THREAD

**Issue by AGiorgetti** [NEventStore/NEventStore#454]
there's no need for custom wrappers anymore, .net core has a flexible logging framework that support external loggers nicely

**Comment by D3-LucaPiombino** [comment]
👍 
This would be very nice .
We adopted structured logging a copule of years ago through all our code base (using **Serilog**).

One of the problem we encountered frequently when using third party libraries that allow to replace the log subsystem (**NEventstore**, **MassTransit**, etc...), is that you need fall back on plain text logging, because the provided adapter interface support only a **string.Format** approach.

From our experience basing the logging adapter on a interface that provide structured data does provide a better solution, even if in the end one ends up sinking log events on a text file, because you can always fold log event into plain text, but not the other way around.

**Comment by alkampfergit** [comment]
I'm not sure that this is really a good approach, because standard framework probably still need the wrapper. If the .NET core logging framework will allow for better functionalities (ex structured logging) it could be interesting, otherwise we could use the wrapper.

**Comment by esbenbach** [comment]
Full Framework does not need the wrapper, it just need a dependency on Microsoft.Extensions.Logging NuGet package.
Some care is probably needed to make sure the version used works on .NET 4.5 (or whatever is the lowest version to be supported).

Not entirely certain which .net standard version the logging extension supports but afaik .NET 4.5 is only netstandard1.2

**Comment by sbiaudet** [comment]
Microsoft.Extensions.Logging support only netstandard 2.0 and netcoreapp3.1. In this case the lowest version will be 4.6.1. Can we up the lowest version supported to 4.6.1.

I propose this implementation

To register LoggerFactory
```
public static class LoggingWireupExtensions
    {
        public static Wireup WithLoggerFactory(this Wireup wireup, ILoggerFactory loggerFactory)
        {
            return wireup.LogTo(type => loggerFactory.CreateLogger(type));
        }

        public static Wireup LogTo(this Wireup wireup, Func<Type, ILogger> logger)
        {
            LogFactory.BuildLogger = logger;
            return wireup;
        }
    }
```
with this LogFactory internal infrastructure class.

  ```
/// <summary>
    ///     Provides the ability to get a new instance of the configured logger.
    /// </summary>
    public static class LogFactory
    {
        /// <summary>
        ///     Initializes static members of the LogFactory class.
        /// </summary>
        static LogFactory()
        {
            var logger = NullLogger.Instance;
            BuildLogger = type => logger;
        }

        /// <summary>
        ///     Gets or sets the log builder of the configured logger.  This should be invoked to return a new logging instance.
        /// </summary>
        public static Func<Type, ILogger> BuildLogger { get; set; }
    }
```

**Comment by AGiorgetti** [comment]
Thanks @sbiaudet , PR accepted.
