### ISSUE TITLE
Access to commit information when deserializing events

### ISSUE THREAD

**Issue by chrischu** [NEventStore/NEventStore#506]
We would like to have access to the various commit properties (timestamp, etc.) when deserializing event messages.

My team needs this because we want to incorporate the commit stamp into our events but do not want to make it optional for old events. With this solution we can just reconstruct the commit stamp during deserialization.

We believe that this is not just a use-case that our team experiences, but that most people using NEventStore will at some point have to do upcasting of their events and then might need access to the commit information.

To avoid any backwards compatibility problems I introduced a `ISerializeEvents` interface that by default just forwards to `ISerialize`. This gives my team the ability to access the commit information when deserializing events while keeping other users' code running.

Of course feedback & improvement wishes for the PRs are welcome and appreciated!

**Comment by AGiorgetti** [comment]
Can't it be done with a custom pipeline hook instead of adding a new interface to the core? 
It seems to me that with a sligtly modified version of the original "EventUpconverterPipelineHook" (that is used to provide upcasting) it can be done easily.
I did something similar in my projects also.
I agree that the original design of that feature could have been more smat and also pass the commit metadata to the event upcaster.

This way you do not need to modify any of the persistence drivers.

**Comment by fschmied** [comment]
> Given that the goal is to enrich events (correct me if I miss something),
> can't it be done with a custom pipeline hook instead of adding a new interface to the core?

I should have clarified that I was talking about upcasting at the _JSON_ level, which needs to occur during deserialization. In the face of that, pipeline hooks are too late, after deserialization has already happened.

(Some context: We originally started with upcasting at the C# level, i.e., where you have C# classes for event version 1, version 2, etc. Back then, the pipeline hook would have worked great for us. But after a few dozen events with a few dozen versions, we switched to JSON-based upcasting. I.e., during deserialization, we take the JSON and convert it to match the newest version. Then we only need C# classes for the latest version of each event. This is a bit like the switch from _"Basic Type Based Versioning"_ to _"Weak Schema"_ in Greg Young's [ebook](https://leanpub.com/esversioning/read#leanpub-auto-weak-schema) on the topic.)

BUT your comment gave @chrischu an idea and he managed to implement a workaround, where he registers a stupid "keep the JSON" deserializer. Then, a pipeline hook can be used to do the _real_ deserialization plus upcasting at the JSON level. So thank you, @AGiorgetti :) .

Still, ideally such a workaround would not be needed, I think.

> This way you do not need to modify any of the persistence drivers.

Do you think the change is too risky/involved to merge it? Or do you think it's just not a good idea to give the metadata to the deserializer?

**Comment by AGiorgetti** [comment]
@fschmied @chrischu ah now I get it! I like the "Weak Schema" idea, opens up new scenarios.

I need to check if it can also be used by other persistence drivers implementation (MongoDB LOL, cause it's only other one actively supported), otherwise it can be an extension limited to the SQL driver only.

**Comment by AGiorgetti** [comment]
After some checks I believe that the new ISerializeEvents should be moved to the SQL driver only, that's because of how the deserialization stage was implemented.

What I'll do is:
- Add the ISerializeEvents interface and default implementation to the SQL  only
- write a note in the changelog explaing the new feature
- Open the PR against "develop" if possible (I'm using GitFlow to manage the repository), So I can make other changes of needed

MongoDB does not need anything like this, I believe the same behavior can be obtained implementing a custom serializer for the "MongoCommit" class (the actual class that's persisted).

**Comment by AGiorgetti** [comment]
Please do the changes, also update the PRs to merge in "develop" branch, thanks!
